version: '3.8'

services:
  nginx:
    container_name: nginx_service
    image: nginx:1.25-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/pma/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf

  php:
    container_name: php_service
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app:rw
    environment:
      - HOST_UID=${UID}
      - HOST_GID=${GID}

  mariadb:
    container_name: mariadb_service
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'symfony7'
      MYSQL_USER: 'symfony7'
      MYSQL_PASSWORD: 'symfony7'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_service
    image: phpmyadmin/phpmyadmin:5.2.1
    depends_on:
      - mariadb
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root

volumes:
  db_data:
